# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
  - job: Test_CentOS
    pool: 
      vmImage: ubuntu-latest
    steps: 
      - script: "sudo apt update"
        displayName: "Running apt update"
      - script: "sudo apt install ansible"
        displayName: "Running ansible install"
      - script: "sudo touch /etc/ansible/hosts"
        displayName: "Running Create ansible hosts file"
      - script: 'sudo echo "win:" | sudo tee -a /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'sudo echo "  hosts:" | sudo tee -a /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'sudo echo "    waap:" | sudo tee -a /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'sudo echo "      ansible_host: localhost" | sudo tee -a /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'sudo echo "    woop:" | sudo tee -a /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'sudo echo "      ansible_host: localhost " | sudo tee -a /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'sudo cat /etc/ansible/hosts'
        displayName: "Running display inventory"
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: NUnit
          testResultsFiles: '**/TestsResults.xml'
