# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
  - job: Test_CentOS
    pool: 
      vmImage: ubuntu-latest
    steps: 
      - script: "sudo apt update"
        displayName: "Running apt update"
      - script: "sudo apt install ansible"
        displayName: "Running ansible install"
      - script: "sudo touch /etc/ansible/hosts"
        displayName: "Running Create ansible hosts file"
      - script: 'echo "win:" >> /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'echo "  hosts:" >> /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'echo "    waap:" >> /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'echo "      ansible_host: localhost" >> /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'echo "    woop:" >> /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - script: 'echo "      ansible_host: localhost " >> /etc/ansible/hosts'
        displayName: "Running dump dummy inventory"
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: NUnit
          testResultsFiles: '**/TestsResults.xml'
